// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD33SUkGX1b0bQPPHu0sdORG40LVms16r4',
    appId: '1:458259203121:android:a6c043982a490ef8a94110',
    messagingSenderId: '458259203121',
    projectId: 'todoapp-66f82',
    databaseURL: 'https://todoapp-66f82-default-rtdb.firebaseio.com',
    storageBucket: 'todoapp-66f82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq1MY5OE1o5VJSATuMwMJdLtbwbudSGnE',
    appId: '1:458259203121:ios:73e748fd0e301800a94110',
    messagingSenderId: '458259203121',
    projectId: 'todoapp-66f82',
    databaseURL: 'https://todoapp-66f82-default-rtdb.firebaseio.com',
    storageBucket: 'todoapp-66f82.appspot.com',
    androidClientId: '458259203121-5ju1opau2pqh5j9aqes7ldfqr56e2f6r.apps.googleusercontent.com',
    iosClientId: '458259203121-7t5ekermg14gh770dp2utngnf4932gpk.apps.googleusercontent.com',
    iosBundleId: 'com.faarukbulut.todoapp',
  );

}